### ISSUE TITLE
Указывать только id группы в конфиге

### ISSUE THREAD

**Issue by BigRedEye** [BigRedEye/notmanytask#15]
Сейчас
```yaml
gitlab:
  group:
    name: ...
    id: ...
```

При этом gitlab.group.name вычисляется из gitlab.group.id
